#!/usr/bin/env python3
"""
Vendor the three UI fonts as local woff2 and generate `src/fonts.css`.

**Why not the CDN.** The page used to pull them from fonts.googleapis.com at
runtime, which is two problems at once in this particular deployment: the panel
is opened on a LAN that is regularly without internet, and the household filters
DNS on both resolvers — a blocklist entry for fonts.gstatic.com (several lists
carry one) would swap the whole interface to a fallback face with no error
anywhere to explain it.

**One file per family, not one per weight.** Google serves these three as
*variable* fonts: the woff2 behind `wght@500`, `600` and `700` of Space Grotesk
is byte-for-byte the same file. Fetching per weight the obvious way downloads it
three times and ships 100 kB of duplicates. The generated `@font-face` therefore
declares a weight *range*, and the browser interpolates.

Latin subset only; the UI is German and English.

Usage:  python scripts/fetch-fonts.py
"""
from __future__ import annotations

import hashlib
import io
import os
import re
import urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, 'src', 'assets', 'fonts')
CSS = os.path.join(HERE, 'src', 'fonts.css')

FAMILIES = {
    'Space Grotesk': ('SpaceGrotesk', '500 700'),
    'Inter': ('Inter', '400 500'),
    'JetBrains Mono': ('JetBrainsMono', '500 600'),
}

URL = ('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700'
       '&family=Inter:wght@400;500&family=JetBrains+Mono:wght@500;600&display=swap')

# Without a modern User-Agent, Google serves ancient formats instead of woff2.
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/126.0 Safari/537.36')


def get(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={'User-Agent': UA}), timeout=60).read()


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    css = get(URL).decode('utf-8')
    blocks = re.findall(r'/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)

    seen: dict[str, tuple[str, str]] = {}   # family -> (filename, unicode-range)
    digests: dict[str, set[str]] = {}
    for subset, block in blocks:
        if subset != 'latin':
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        if fam not in FAMILIES:
            continue
        url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
        data = get(url)
        digests.setdefault(fam, set()).add(hashlib.sha256(data).hexdigest())
        if fam in seen:
            continue
        stem, _ = FAMILIES[fam]
        name = '%s.woff2' % stem
        io.open(os.path.join(OUT, name), 'wb').write(data)
        rng = re.search(r'unicode-range:\s*([^;]+);', block)
        seen[fam] = (name, rng.group(1).strip() if rng else '')
        print('  %-22s %6d bytes' % (name, len(data)))

    for fam, ds in digests.items():
        if len(ds) != 1:
            print('  NOTE: %s is not a single variable file (%d distinct weights) — '
                  'the weight range below is wrong for it.' % (fam, len(ds)))

    lines = [
        '/*',
        ' * Self-hosted UI fonts — generated by scripts/fetch-fonts.py, do not edit.',
        ' *',
        ' * They used to load from fonts.googleapis.com at runtime. Two reasons they',
        ' * do not any more, both specific to where this add-on runs: the panel is',
        ' * opened on a LAN that is regularly without internet, and the household',
        ' * filters DNS on both resolvers — a blocklist entry for fonts.gstatic.com',
        ' * would swap the whole interface to a fallback face, silently.',
        ' *',
        ' * One file per family: all three are variable fonts, so the woff2 behind',
        ' * weight 500, 600 and 700 is the same bytes. Hence a weight *range*.',
        ' *',
        ' * They live under src/assets/, not public/: the panel is served behind a',
        ' * Home Assistant Ingress prefix, so an absolute /fonts/... URL is a 404.',
        ' * Importing them lets Vite emit a URL relative to the stylesheet, which',
        ' * resolves correctly under any prefix.',
        ' */',
        '',
    ]
    for fam, (name, rng) in seen.items():
        _, weights = FAMILIES[fam]
        lines += [
            '@font-face {',
            "  font-family: '%s';" % fam,
            '  font-style: normal;',
            '  font-weight: %s;' % weights,
            '  font-display: swap;',
            "  src: url('./assets/fonts/%s') format('woff2');" % name,
        ]
        if rng:
            lines.append('  unicode-range: %s;' % rng)
        lines += ['}', '']

    io.open(CSS, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    print('%d families -> src/fonts.css' % len(seen))


if __name__ == '__main__':
    main()
